=== FakeApate/ai-poppins/ui/new_schema/newschema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Task Schema",
  "type": "object",
  "required": ["name", "priority", "schedule"],
  "properties": {
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "category": {
      "type": "string"
    },
    "priority": {
      "type": "integer"
    },
    "data": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/data_entry"
      }
    },
    "schedule": {
      "$ref": "#/$defs/task_schedule"
    }
  },
  "$defs": {
    "data_entry": {
      "type": "object",
      "properties": {
        "typedef": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      }
    },
    "task_schedule": {
      "type": "object",
      "properties": {
        "duration": {
          "type": "string",
          "format": "time",
          "required": true
        },
        "repeat_frequency": {
          "type": "string",
          "enum": ["none", "daily", "weekly", "monthly"]
        },
        "repeat_days": {
          "type": "string",
          "pattern": "^0b[01]+$"
        }
      },
      "description": "The scheduling information for the task",
      "required": true,
      "if": {
        "properties": {
          "repeat_days": {
            "not": {
              "enum": [null]
            }
          }
        }
      },
      "then": {
        "required": ["repeat_frequency"]
      }
    }
  }
}

=== FakeApate/ai-poppins/ui/mongoPlayground/clean_bathroom.json
{
  "name": "Clean the bathroom",
  "description": "Thoroughly clean the bathroom, including sink, toilet, shower, and floor.",
  "category": "Household chores",
  "priority": 7,
  "data": [],
  "schedule": {
    "duration": "00:45:00",
    "repeat_frequency": "monthly",
    "repeat_days": "0b1"
  }
}
